env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: "-1001510035003"
    TG_TOKEN: "ENCRYPTED[!c262f1e147caa787ff1ff0923ce95604e26b01fdedf819bd14e5d9d2a9028d7dd8af95f4f364d841ea4819891d46c76a!]"

    # github
    token: "ENCRYPTED[!69e5f5eb05bcde4b07cd6c1fd6f5513664d7e98c279275e32335809786ffc600e7b8d0d34ca5ed19621d73675179f066!]" # main id
    gh: "ENCRYPTED[!2d216e11d390b24637945eead7a7daa9d3ae3cb0907ae24c3763a05f725187ac5836f88fb3e6e71a180eea6f440ac023!]" # main id

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/upload.sh)"
