#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# wait for function script to clone
while true; do
    if [ -f "/tmp/ci/function" ]; then
        . /tmp/ci/function
        break
    else
        sleep 1
    fi
done

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

git config --global user.name "ImSpiDy"
echo "switching account" 
gh config set -h github.com
login_main # main id
git config --global credential.helper '!gh auth git-credential'

# Sync source
#https://github.com/crdroid-security/android.git -b 11.0
repo init --depth=1 --no-repo-verify -u https://github.com/JunkYard-XD/manifest.git -b 11 --git-lfs -g default,-mips,-darwin,-notdefault

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j10

#rm -rf system/bt
#git clone --single-branch https://github.com/crdroid-security/android_system_bt -b 11.0 system/bt && git -C system/bt reset --hard HEAD~3

# tree
if [ $K19 == 1 ]; then
git clone --depth=1 --single-branch https://github.com/ImSpiDy/sonix_kernel_sdm660 kernel/xiaomi/sdm660 -b 11
#git -C kernel/xiaomi/sdm660 revert --no-edit 82c22783962ef202b2a6df7f09d47616f6f45c07
#git -C kernel/xiaomi/sdm660 revert --no-edit edf92cc79b545136824f212490108846b27af5fc
#sed -i '/CONFIG_INITRAMFS_IGNORE_SKIP_FLAG=/s/.*/CONFIG_INITRAMFS_IGNORE_SKIP_FLAG=n/' kernel/xiaomi/sdm660/arch/arm64/configs/lavender_defconfig
#hevc fix
curl https://github.com/Atom-X-Devs/scarlet_xiaomi_sdm660/commit/572d01152a3ad83fc401c1af19adbdf39fe8a7e1.patch | git -C kernel/xiaomi/sdm660 am
#git -C kernel/xiaomi/sdm660 apply drop_rdp.p
else
git clone --depth=1 --single-branch https://github.com/ImSpiDy/kernel_xiaomi_lavender-4.4 kernel/xiaomi/sdm660 -b snx-qti
git -C kernel/xiaomi/sdm660 apply QTI_HAPTICS.p
fi
git clone https://github.com/ImSpiDy/device_xiaomi_lavender device/xiaomi/lavender -b 11
git clone --depth=1 https://github.com/ImSpiDy/device_xiaomi_sdm660-common device/xiaomi/sdm660-common -b 11

git clone --depth=1 --single-branch https://github.com/ImSpiDy/vendor_lavender vendor/xiaomi/lavender -b 11
git clone --depth=1 --single-branch https://github.com/ImSpiDy/vendor_xiaomi_sdm660-common vendor/xiaomi/sdm660-common -b 11

#rm -rf hardware/xiaomi
#git clone --depth=1 https://github.com/arrowos-devices/android_hardware_xiaomi hardware/xiaomi -b arrow-13.1

#rm -rf device/qcom/sepolicy-legacy-um
#git clone --depth=1 https://github.com/ArrowOS/android_device_qcom_sepolicy-legacy-um device/qcom/sepolicy-legacy-um -b arrow-13.1

#rm -rf device/xiaomi/lavender/libhidl
#rm -rf hardware/xiaomi/megvii/*.bp

# patch
#rm -rf /tmp/rom/bionic
#git clone --depth=1 https://github.com/wHo-EM-i/bionic -b vos13

# Hals
rm -rf hardware/qcom-caf/sdm660
sed -i 's|QCOM_HARDWARE_VARIANT := msm8998|QCOM_HARDWARE_VARIANT := sdm660|' vendor/*/config/B*Qcom.mk
if [ $K19 == 1 ]; then
#sed -i 's|QCOM_HARDWARE_VARIANT := msm8998|QCOM_HARDWARE_VARIANT := sdm660|' vendor/*/config/B*Qcom.mk
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_audio hardware/qcom-caf/sdm660/audio -b 11-caf-sdm660
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_media hardware/qcom-caf/sdm660/media -b 11-caf-sdm660
git clone --depth=1 https://github.com/wHo-EM-i/hardware_qcom_display hardware/qcom-caf/sdm660/display -b 11-caf-sdm660
else
#sed -i 's|QCOM_HARDWARE_VARIANT := sdm660|QCOM_HARDWARE_VARIANT := msm8998|' vendor/*/config/B*Qcom.mk
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_audio hardware/qcom-caf/sdm660/audio -b sdm660-4.4
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_media hardware/qcom-caf/sdm660/media -b sdm660-4.4
git clone --depth=1 https://github.com/wHo-EM-i/hardware_qcom_display hardware/qcom-caf/sdm660/display -b 11-9.2.r1
fi
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_camera hardware/qcom-caf/sdm660/camera -b sdm660-9.2.r1

# keys
#git clone --depth=1 https://github.com/Los-Ext/vendor_lineage-priv_keys vendor/lineage-priv/keys
git clone https://github.com/Nub-XD/vendor_lavender-priv_keys vendor/lineage-priv/keys
echo "-include vendor/lineage-priv/keys/keys.mk" >> vendor/*/config/common.mk

#patch
rm -rf device/qcom/sepolicy-legacy-um
git clone https://github.com/raiyanbinmohsin/device_qcom_sepolicy-legacy-um device/qcom/sepolicy-legacy-um
git -C device/qcom/sepolicy-legacy-um revert -n b63cd988f7e7df3d54a97285f354476760edf7ae
# build/soong
curl https://github.com/wHo-EM-i/build_soong/commit/42df79cee0b1eec108a71affcf3ae841613b9a0c.patch | git -C build/soong am
#curl https://github.com/wHo-EM-i/build_soong/commit/809cf30f6ee3183d630c40b5eef375fe1fd965a7.patch | git -C build/soong am
curl https://github.com/wHo-EM-i/build_soong/commit/1f4a7bed507a34ca6e46a5ab5b4017899133cab0.patch | git -C build/soong am
curl https://github.com/wHo-EM-i/build_soong/commit/0a769f9d183a692b9fd56dabd77aec7b2a80d980.patch | git -C build/soong am
# bionic
#curl https://github.com/crdroidandroid/android_bionic/commit/1bc81a661fac286b709f6c424e260ff863dfad5c.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/35990d0980cacda546da37870d26f19058f2ce17.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/1b0f29cc939cd54b6d05d831e7bdb027df26d48f.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/51eede079a2ffea774387b5bc85acf3045a2d540.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/39d3922e99268aae398bff4be4f665d04a57e996.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/503eee1d788c15e489a565d1e309b89c926f40af.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/95558dd34bf0b7c8fa995f72974a0d54ec5bd044.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/39d0bc4270a07cb5212f4deacf53d6585a0607f6.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/aac77981473662b7a71f2a1fa2463bff0f423efa.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/48cec51f241f87811dabc65e27fc5bb094676231.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/54de6110d3c55be0573c358661ce0439f5bd25e0.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/4114593175e1bc96925be734a80551c6c1502379.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/fbacd1563238aa2518971171e4d95cca61326cb8.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/7d66f1fb333114f7e35a2bd33e428d66b70e72ca.patch | git -C bionic am

# hax
# fwb
#rm -rf frameworks/base; git clone --depth=1 https://github.com/JunkYard-XD/android_frameworks_base frameworks/base -b 11.0
git -C frameworks/base fetch https://github.com/JunkYard-XD/android_frameworks_base -t 11.0
git -C frameworks/base cherry-pick d8be6329bcdfc9f384a350d04008f7e6853512eb^..3b6a25be3ad541488105bea9d7acdefae23f88e1
# PPU
git -C frameworks/base cherry-pick 87b4c62e3cbab2da36656dfddaf750aa1e008691
#git clone --depth=1 https://gitlab.com/Project-Nexus/nexus-clang.git prebuilts/clang/host/linux-x86/custom-clang -b nexus-14

# qti powerhal
rm -rf /tmp/rom/vendor/qcom/opensource/power
git clone --depth=1 https://github.com/JunkYard-XD/android_vendor_qcom_opensource_power vendor/qcom/opensource/power -b 11.0

git config --global user.name "$CIRRUS_REPO_OWNER"
echo "switching account" && gh auth logout
login_main # main id
gh config set -h github.com

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt


dload_out () {
tg "Downloading OUT backup"
down $cache_link/releases/download/${rom_name}/${rom_name}-${branch_name}_out.zip.001
down $cache_link/releases/download/${rom_name}/${rom_name}-${branch_name}_out.zip.002
down $cache_link/releases/download/${rom_name}/${rom_name}-${branch_name}_out.zip.003
down $cache_link/releases/download/${rom_name}/${rom_name}-${branch_name}_out.zip.004
down $cache_link/releases/download/${rom_name}/${rom_name}-${branch_name}_out.zip.005
down $cache_link/releases/download/${rom_name}/${rom_name}-${branch_name}_out.zip.006
down $cache_link/releases/download/${rom_name}/${rom_name}-${branch_name}_out.zip.007
down $cache_link/releases/download/${rom_name}/${rom_name}-${branch_name}_out.zip.008
down $cache_link/releases/download/${rom_name}/${rom_name}-${branch_name}_out.zip.009

# Extract out so ci can use it
if [ -e *_out.zip.001 ]; then
echo "• Extracting OUT •"
time 7za x *_out.zip.001
fi
if [ -e out.tar.gz ]; then
time tar xf out.tar.gz
fi

if [ -e *_out.zip.001 ]; then
tg "$rom_name out downloaded successfully!
Total Size: $(du -sh ${PWD}/out | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"
else
echo "Skipping OUT Download on 1st build..!"
fi
}

#check_build_type
#case "$build_type" in
#		 C|c)
#		 tg "Skipping OUT Download on Clean build"
#		 ;; # else
#		 *)
#		 #dload_out
#esac

rm -rf *_out.zip.* out.tar.gz

neofetch
